import { type NextPage } from "next";
import Head from "next/head";
import { useState, type FormEventHandler } from "react";
import Task from "../component/task";
import { trpc } from "../utils/trpc";
import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";

const Todo: NextPage = () => {
  const router = useRouter();
  const util = trpc.useContext();
  const [task, setTask] = useState("");
  const { data: todos = [] } = trpc.todo.getAll.useQuery();
  const { data: session, status } = useSession();
  const createTodo = trpc.todo.create.useMutation({
    onSuccess() {
      util.todo.invalidate();
    },
  });

  const handleSubmit: FormEventHandler<HTMLFormElement> = async (e) => {
    e.preventDefault();
    await createTodo.mutateAsync({ task });
    setTask("");
  };

  if (status == "loading") {
    return <p>Loading ...</p>;
  }
  if (status == "unauthenticated") {
    router.push("/login");
    return <p>Access denied!</p>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center">
        <div className="absolute top-4 right-4">
          Welcome {session?.user?.email}
          <button
            onClick={() => signOut({ callbackUrl: "/login" })}
            className="ml-4 font-semibold text-purple-800 underline underline-offset-2"
          >
            Logout?
          </button>
        </div>
        <div className="mx-auto w-full px-4 py-8 shadow lg:w-1/3">
          <div className="mb-6 flex items-center">
            <h1 className="mr-6 text-4xl font-bold text-purple-600">
              {" "}
              TO DO APP
            </h1>
          </div>
          <form onSubmit={handleSubmit} className="relative">
            <input
              onChange={(e) => setTask(e.target.value)}
              value={task}
              name="task"
              type="text"
              placeholder="What needs to be done today?"
              className="border-grey-600 w-full rounded border px-2 py-3 outline-none"
            />
          </form>
          <ul className="list-reset">
            {todos.map((todo) => (
              <Task key={todo.id} todo={todo} />
            ))}
          </ul>
        </div>
      </div>
    </>
  );
};

export default Todo;
